add verbosity to pg connections for the backend app
kumahq/kuma-demo pull request #165
Opened 2024-01-31 16:02 UTC by bcollard

Signed-off-by: Baptiste Collard <9626829+bcollard@users.noreply.github.com>

Add DNS lookup for the PostgreSQL DB and improve logging for the backend nodejs app.

2024-02-01 09:28 UTC, slonka requested changes
couple of things to change

2024-02-01 09:28 UTC, slonka commented on .github/workflows/docker-build-push.yaml
> +        uses: actions/checkout@v4
we're locking  to specific commits in other repos, please do that as well here:

```suggestion
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
```

2024-02-01 09:28 UTC, slonka commented on .github/workflows/docker-build-push.yaml
> +
```suggestion

```

2024-02-01 09:28 UTC, slonka commented on api/app/postgresql.js
> +dnsPromises = dns.promises;
Is `dnsPromises` declared anyway?

```suggestion
const dnsPromises = dns.promises;
```

2024-02-01 09:28 UTC, slonka commented on api/app/postgresql.js
> +      logger.error("Release");
why is this an error? 

```suggestion
      logger.info("Release");
```

2024-02-01 09:28 UTC, slonka commented on api/index.js
> +      // logger.info('result: ' + JSON.stringify(results));
leftover from debugging? either uncomment or remove

2024-02-01 20:55 UTC, bcollard commented
Thanks for the review.
All suggestions were applied.

2024-02-02 07:14 UTC, slonka approved these changes

2024-03-28 09:47 UTC, slonka commented
@bcollard - is this PR ready to be merged?

2024-04-01 16:27 UTC, bcollard commented
Hey! Sorry about the delay! 
Yes, it's ready for another round of review.

Summary:
- pinned the version of docker base images
- log DNS details about the Postgres Host
- switched to full async CRUD methods 
- adopted PINO as the underlying logging system
- use GHA to create AMD and ARM docker images
- use GHA to push images to a docker hub account that should be configured with GHA Secrets:
```yaml
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
```

2024-04-10 08:33 UTC, lahabana reviewed
Thx!

2024-04-10 08:33 UTC, lahabana commented on .github/workflows/docker-build-push.yaml
> +          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kuma-demo-fe:latest
```suggestion
          tags: ${{ vars.DOCKER_REPOSITORY || vars.DOCKERHUB_USERNAME }}/kuma-demo-fe:latest
```

2024-07-25 07:42 UTC, jakubdyszkiewicz approved these changes

2024-07-25 07:42 UTC, merged